CREATE SEQUENCE BOARD_SEQ;
CREATE TABLE BOARD(
	BOARDNO NUMBER PRIMARY KEY,
	BOARDTITLE VARCHAR2(500) NOT NULL,
	BOARDCONTENT VARCHAR2(4000) NOT NULL,
	BOARDWRITER VARCHAR2(200) NOT NULL,
	BOARDREGDATE DATE NOT NULL
)

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'BOARD TITLE1', 'BOARD CONTENT1', 'BOARD WRITER1', SYSDATE);